### ISSUE TITLE
Improve Events

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#361]
The events should be reworked to the following criteria:
- [ ] provide all events possible to allow for more hooks into the system
- [x] move events to new storage, like _data #334 
- [ ] provide all meaningful information in a more structured and understandable way #391 
- [ ] keep in mind that a revert method #189 will be implemented in the future
